<header class="max-w-sm md:max-w-xl mx-auto mt-20 text-center">
    <h1 class="text-4xl">
        <span class="text-blue-500">Artificial Advice</span> generated by Artificial Intelligence. 🤖 
    </h1>
    <h2 class="mt-3 text-lg">WARNING: May contain useless information.</h2>

    <div class="space-y-2 md:space-y-0 md:space-x-4 mt-8">
        <!--  Category -->
        <div class="relative md:inline-flex items-center bg-gray-100 rounded-xl">
            <x-category-dropdown />
        </div>
        <!--  AI Writer -->
        <div class="relative md:inline-flex items-center bg-gray-100 rounded-xl">
            <x-writer-dropdown />
        </div>

        <!-- Search -->
        <div class="md:inline-flex">
            <form method="GET" action="/">
                @if (request('category'))
                    <input type="hidden" name="category" value="{{ request('category') }}">
                @endif
                @if (request('writer'))
                    <input type="hidden" name="writer" value="{{ request('writer') }}">
                @endif

                <input class="bg-gray-100 rounded-xl px-3 py-2 text-sm w-full font-semibold" type="text"
                    name="search" placeholder="Search..." value="{{ request('search') }}">
            </form>
        </div>
    </div>
</header>