<header class="max-w-sm md:max-w-xl mx-auto mt-20 text-center">
    <h1 class="text-4xl">
        <span class="text-blue-500">Artificial Advice</span> generated by Artificial Intelligence. 🤖 
    </h1>
    {{-- <h2 class="mt-3">Artificial advice generated by artificial intelligence.</h2> --}}

    {{-- <h2 class="inline-flex mt-2">By @Luk3-V <img src="/images/lary-head.svg"
                                                       alt="Head of Lary the mascot"></h2>

    <p class="text-sm mt-14">
        Another year. Another update. We're refreshing the popular Laravel series with new content.
        I'm going to keep you guys up to speed with what's going on!
    </p> --}}

    <div class="space-y-2 md:space-y-0 md:space-x-4 mt-8">
        <!--  Category -->
        <div class="relative md:inline-flex items-center bg-gray-100 rounded-xl">
            <x-category-dropdown />
        </div>
        <!--  AI Writer -->
        <div class="relative md:inline-flex items-center bg-gray-100 rounded-xl">
            <x-writer-dropdown />
        </div>


        <!-- Other Filters -->
        {{-- <div class="relative flex lg:inline-flex items-center bg-gray-100 rounded-xl">
            <select class="flex-1 appearance-none bg-transparent py-2 pl-3 pr-9 text-sm font-semibold">
                <option value="category" disabled selected>Other Filters
                </option>
                <option value="foo">Foo
                </option>
                <option value="bar">Bar
                </option>
            </select>

            <svg class="transform -rotate-90 absolute pointer-events-none" style="right: 12px;" width="22"
                 height="22" viewBox="0 0 22 22">
                <g fill="none" fill-rule="evenodd">
                    <path stroke="#000" stroke-opacity=".012" stroke-width=".5" d="M21 1v20.16H.84V1z">
                    </path>
                    <path fill="#222"
                          d="M13.854 7.224l-3.847 3.856 3.847 3.856-1.184 1.184-5.04-5.04 5.04-5.04z"></path>
                </g>
            </svg>
        </div> --}}

        <!-- Search -->
        <div class="md:inline-flex">
            <form method="GET" action="/">
                @if (request('category'))
                    <input type="hidden" name="category" value="{{ request('category') }}">
                @endif
                @if (request('writer'))
                    <input type="hidden" name="writer" value="{{ request('writer') }}">
                @endif

                <input class="bg-gray-100 rounded-xl px-3 py-2 text-sm w-full font-semibold" type="text"
                    name="search" placeholder="Search..." value="{{ request('search') }}">
                {{-- <input type="text" name="search" placeholder="Search..."
                       class="bg-transparent placeholder-black font-semibold text-sm w-full md:w-32 inline-flex"
                       value="{{ request('search') }}"> --}}
            </form>
        </div>
    </div>
</header>