<style>
    #content h1 {
        font-size: 1.5rem !important;
        line-height: 2rem !important;
        font-weight: 600 !important;
        margin-top: 2rem !important;
    }
    #content h2 {
        font-size: 1.25rem !important;
        line-height: 1.75rem !important;
        font-weight: 600 !important;
    }
    #content ol {
        list-style: decimal !important;
        padding-left: 2rem;
    }
    #content ol > li::marker {
        font-weight: bold;
    }
    #content p {
        margin: 1rem 0 !important;
    }
    @media (min-width: 768px) {
        #content h1 {
            margin-top: 3rem !important;
            margin-bottom: 1.5rem !important;
        }
        #content h2 {
            margin-top: 2rem !important;
        }
    }
</style>

<x-layout>
    <main class="max-w-lg md:max-w-6xl mx-auto mt-10 md:mt-20 space-y-6">
        <div class="max-w-4xl mx-auto">
            <a href="/"
                class="transition-colors duration-300 relative inline-flex items-center text-lg hover:text-blue-500 hover:underline">
                <svg width="22" height="22" viewBox="0 0 22 22" class="mr-2">
                    <g fill="none" fill-rule="evenodd">
                        <path stroke="#000" stroke-opacity=".012" stroke-width=".5" d="M21 1v20.16H.84V1z">
                        </path>
                        <path class="fill-current"
                            d="M13.854 7.224l-3.847 3.856 3.847 3.856-1.184 1.184-5.04-5.04 5.04-5.04z">
                        </path>
                    </g>
                </svg>

                Back to Posts
            </a>
        </div>

        <article class="max-w-4xl mx-auto md:grid md:grid-cols-12 gap-x-10">
            <div class="col-span-4 md:text-center mb-10">
                <img src="{{ asset($post->thumbnail) }}" alt="" class="rounded-xl">

                <p class="block text-gray-400 text-xs mt-4">
                    Image generated by DALL-E
                </p>

                <div class="flex items-center md:justify-center text-sm mt-4">
                    <img src="{{ asset($post->writer->avatar) }}" alt="avatar" width="50" height="50" class="rounded">
                    <div class="ml-3 text-left">
                        <a href="/?writer={{ $post->writer->slug }}"><h5 class="font-bold hover:underline">{{ $post->writer->name }}</h5></a>
                        <a href="{{ $post->writer->url }}" class="hover:underline">{{ $post->writer->url }}</a>
                    </div>
                </div>
            </div>

            <div class="col-span-8">
                <div class="space-x-2 mb-6">
                    <x-category-button :category="$post->category"/>
                </div>

                <h1 class="font-bold text-3xl md:text-4xl mb-4">
                    {{ $post->title }}
                </h1>

                <p class="block text-gray-400 text-xs mb-10">
                    <time>{{ $post->created_at->format('F j, Y, g:i a') }}</time>
                </p>

                <div id="content" class="space-y-4 md:text-lg leading-loose">
                    {!! $body !!}
                </div>
            </div>

            <section class="col-span-8 col-start-5 mt-20 space-y-6">
                <h2 class="text-xl font-bold">Comments</h2>

                @include('posts._comment-form')

                @foreach ($post->comments as $comment)
                    <x-post-comment :comment="$comment"/>
                @endforeach
            </section>
        </article>
    </main>
</x-layout>